version: '3.0'
services:
  web:
    build: ./asp-bingo.Web
    image: olivernybo/asp-bingo_web
    restart: always
    ports:
      - 5001:80
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3-management
    restart: always
    expose: 
      - 5672
      - 5671
    ports:
      - 15672:15672
    logging:
      driver: none